name: gaussian_splatting_with_diffusion
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit-dev
  - plyfile
  - python
  - pip=22.3.1
  - tqdm
  - pip:
      - diffusers[torch]
      - ffpb
      - plyfile
      - torch
      - torchaudio
      - torchmetrics
      - torchvision
      - submodules/gaussian-splatting/submodules/diff-gaussian-rasterization
      - submodules/gaussian-splatting/submodules/simple-knn
      - submodules/gaussian-splatting/submodules/fused-ssim
      - opencv-python
      - joblib
